spring.application.name=demo

# Server port
server.port=9090

# H2 DB config
spring.datasource.url=jdbc:h2:file:./prtracker-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Github token (replace with your PAT)
# github.token=ADD_YOUR_GITHUB_PAT_HERE

# Logging
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.web=DEBUG
